
name: scipy-2023-pydantic-tutorial

channels:
  - conda-forge

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - pydantic=1.10.7
  - requests
  - jupyter
  - pandas
  - matplotlib
  - mypy
  - PyYAML
  - toml
  - pre-commit
