name: CI-Conda
on: [push, pull_request]
jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Conda
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-file: environment.yaml
          init-shell: bash
      - name: Run check
        run: |
          python check-setup.py
      - name: Run notebooks
        shell: bash -el {0}
        run: |
          jupyter nbconvert --execute --to html notebooks/*.ipynb
