name: CI
on: [push, pull_request]
jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install all dependencies
        run: |
          pip install -r requirements.txt
      - name: Run check
        run: |
          python check-setup.py --strict
      - name: Run notebooks
        run: |
          jupyter nbconvert --execute --to html notebooks/*.ipynb