name: Deploy Pages
on:
  push:
    branches:
      - main
jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install all dependencies
        run: |
          pip install -r requirements.txt
      - name: Run notebooks and copy to temp
        run: |
          jupyter nbconvert --output-dir='./page' --execute --to markdown notebooks/*.ipynb
          cp -r ./page ~/tmp
          git checkout gh-pages
          rm -rf *
          cp -r ~/tmp/page/* .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        if: success()
        with:
          push_options: '--force'
          commit_options: '--no-verify --amend'
          commit_author: GitHub Actions <actions@github.com>
          commit_message: Update tutorial page